"""empty message

Revision ID: 77303f0cda4a
Revises: c3694ce1150c
Create Date: 2023-03-11 09:32:06.593898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77303f0cda4a'
down_revision = 'c3694ce1150c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.String(length=1000), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=1000), nullable=False))
        batch_op.drop_column('review')

    # ### end Alembic commands ###